on:
  push:
    branches: ['**']

jobs:
  build_mooc:
    runs-on: ubuntu-latest
    name: Build MOOC
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r mooc_src/requirements.txt
      - name: Scaffold MOOC
        run: mkdir mooc
      - name: Build MOOC
        run: cd mooc_src; bash render.sh
      - name: Copy supporting files
        run: cp -r mooc_src/support mooc/support
      - name: Copy slides
        run: cp -r mooc_src/written mooc/written
      - name: Copy style
        run: cp mooc_src/mooc.css mooc/mooc.css
      - name: Copy logic
        run: cp mooc_src/lesson.js mooc/lesson.js
      - name: Upload MOOC directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mooc
          path: ./mooc
  upload_files:
    runs-on: ubuntu-latest
    name: Upload
    environment: deploy
    if: github.ref == 'refs/heads/main'
    needs: build_mooc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove git directory
        run: rm -r .git
      - name: Remove workflow directory
        run: rm -r .github
      - name: Remove mooc_src
        run: rm -r mooc_src
      - name: Download mooc artifact
        uses: actions/download-artifact@v4
        with:
          name: mooc
          path: ./mooc
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SFTP_HOST }} > ~/.ssh/known_hosts
      - name: Upload
        run: |
          scp -r ./* ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }}:./mooc.interactivedatascience.courses/
